// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crud.model.db;

#nullable disable

namespace crud.Migrations
{
    [DbContext(typeof(Db_crud))]
    [Migration("20220928022814_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("crud.model.Pizzas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nomePizza")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("qtdConsumida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tamanhoPizza")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("crud.model.Refrigerante", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nomeRefri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("qtdConsumida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tamanhoMls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Refrigerante");
                });
#pragma warning restore 612, 618
        }
    }
}
